dist: artifacts
before:
   hooks:
     - go mod download

builds:
  - env:
    - CGO_ENABLED=0
    main: ./cmd/
    goos:
    - linux
    - darwin
    - freebsd
    goarch:
    - amd64
    - arm
    - arm64
    ldflags: -s -w
    binary: smtp2http 